### PR TITLE
Feat/update with upstream repo

### PR DESCRIPTION
**Pull request by wilsouza**
Update this role with [geerlingguy/ansible-role-nginx](https://github.com/geerlingguy/ansible-role-nginx)

### CODE REVIEW

**Comment by wilsouza** [comment]
@mtulio I see some changes that you made. Can you check if this merge not brake you changes, pls?
The last 2 commits specifics.

**Review by AndreZiviani — APPROVED** [review]
I think it doesn't break our current state, but lets wait for someone else's review

**Review by mtulio — APPROVED** [review]
It probably will break some of our usage, we are using this role a lot in dozens of repo, but it's very important to keep it sync with upstream. For the usage side, is recommended to use this version, otherwise we can pin the commit version on the submodule (our usage model).

Thanks for the upgrade!

**Comment by AndreZiviani** [comment]
Agreed, if it breaks something later its an incentive to upgrade there aswell :P

**Pull request merged**
